package weatherApplication;

/**
 * Created by Karolina Pasierbiewicz
 */
public class CityNameList {

    String[] possibleSuggestions = {
            "Abrau-Dyurso",
            "Adelaide",
            "Adelanto",
            "Adler",
            "Adygeysk",
            "Agia Trias",
            "Agra",
            "Agrinio",
            "Ahmadabad",
            "Aigues-Mortes",
            "Ajmer",
            "Akhtanizovskaya",
            "Aksay",
            "Alabushevo",
            "Albino",
            "Aleksandrov",
            "Alekseyevka",
            "Alice Springs",
            "Allahganj",
            "Almaty",
            "Altofonte",
            "Altopascio",
            "Altukhovo",
            "Alushta",
            "Anapskaya",
            "Andzhiyevskiy",
            "Angarsk",
            "Apsheronsk",
            "Aracena",
            "Arad",
            "Arafo",
            "Arkhipo-Osipovka",
            "Armidale",
            "Armstrong",
            "Arsaki",
            "Aruja",
            "Ashitkovo",
            "Ashukino",
            "Asipovichy",
            "Athelstone",
            "Attard",
            "Ayutinskiy",
            "Babruysk",
            "Babushkin",
            "Babynino",
            "Bagayevskaya",
            "Bakhchysaray",
            "Balaguer",
            "Balaklava",
            "Bangkok",
            "Barakaldo",
            "Baran",
            "Barcarena",
            "Barcellona-Pozzo di Gotto",
            "Barcelona",
            "Barguzin",
            "Barrafranca",
            "Barvikha",
            "Basel",
            "Basi",
            "Bavleny",
            "Bawal",
            "Bayganin",
            "Baykalsk",
            "Beaufort West",
            "Becancour",
            "Bega",
            "Behror",
            "Beinette",
            "Belaya Glina",
            "Belaya Kalitva",
            "Belgorod",
            "Beloozerskiy",
            "Belorechensk",
            "Beppu",
            "Berdyansk",
            "Berehove",
            "Bereza",
            "Berezhani",
            "Bergara",
            "Bhairahawa",
            "Bharatpur",
            "Bharatpur",
            "Bichvinta",
            "Bilhorod-Dnistrovskyy",
            "Bilma",
            "Bilohirsk",
            "Birkirkara",
            "Birobidzhan",
            "Bisingen",
            "Bobrovytsya",
            "Bodh Gaya",
            "Bogolyubovo",
            "Boksburg",
            "Bolokhovo",
            "Bolshiye Vyazemy",
            "Bolzano",
            "Bonar",
            "Bor",
            "Borghetto Santo Spirito",
            "Borovoy",
            "Boryspil",
            "Botrugno",
            "Bovec",
            "Box Elder",
            "Brasov",
            "Brest",
            "Brno",
            "Broken Hill",
            "Bronnitsy",
            "Brovary",
            "Bryansk",
            "Buderim",
            "Buffalo",
            "Bugulma",
            "Bulandshahr",
            "Burnaby",
            "Burunday",
            "Buynichy",
            "Cabezon de la Sal",
            "Cagliari",
            "Caldonazzo",
            "Carbonne",
            "Carmagnola",
            "Cartigliano",
            "Casas Ibanez",
            "Casino",
            "Casola Valsenio",
            "Castelnuovo di Garfagnana",
            "Castelsarrasin",
            "Castione della Presolana",
            "Chamical",
            "Chatham-Kent",
            "Chazelles-sur-Lyon",
            "Chekhov",
            "Chernaya",
            "Chernogolovka",
            "Chhala",
            "Chhata",
            "Chikushino-shi",
            "Chillan",
            "Chinchon",
            "Chipping Norton",
            "Chitose",
            "Chokurdakh",
            "Chornomorske",
            "Chortiatis",
            "Chukhloma",
            "Cinisello Balsamo",
            "Ciudad Bolivar",
            "Ciudad Guayana",
            "Clarence-Rockland",
            "Cobar",
            "Cody",
            "Coffs Harbour",
            "Colby",
            "Coro",
            "Coyoacan",
            "Creazzo",
            "Crema",
            "Cresco",
            "Crossfield",
            "Cundletown",
            "Dagomys",
            "Dahlonega",
            "Dairago",
            "Dausa",
            "Davydovo",
            "Dee Why",
            "Delhi",
            "Delvada",
            "Deutschlandsberg",
            "Deutsch-Wagram",
            "Dharuhera",
            "Dibai",
            "Dimitrovgrad",
            "Diu",
            "Divnomorskoye",
            "Dmitrov",
            "Doha",
            "Dolianova",
            "Dolores",
            "Dolzhanskaya",
            "Domodedovo",
            "Donetsk",
            "Donskoye",
            "Drezna",
            "Druzhba",
            "Druzhba",
            "Dubbo",
            "Dubna",
            "Dubovskoye",
            "Dubrowna",
            "Dzerzhinskiy",
            "Dzhankoy",
            "Dzhubga",
            "East Jordan",
            "Edmonton",
            "Edremit",
            "Edson",
            "Ehingen",
            "Ejea de los Caballeros",
            "Ejido",
            "El Vigia",
            "Elche",
            "Elda",
            "Elefsina",
            "Elektrogorsk",
            "Elektrostal",
            "Elektrougli",
            "Ellis",
            "Eppelheim",
            "Erythres",
            "Esparreguera",
            "Etrechy",
            "Evans Head",
            "Falcade",
            "Farah",
            "Faridabad",
            "Fatehpur Sikri",
            "Feodosiya",
            "Ferrara",
            "Firenze",
            "Firozpur Jhirka",
            "Foggia",
            "Forano",
            "Foros",
            "Fosforitnyy",
            "Frankenmarkt",
            "Fryanovo",
            "Fryazevo",
            "Fryazino",
            "Fullarton",
            "Furmanov",
            "Fusignano",
            "Gagra",
            "Galatsi",
            "Galich",
            "Gaspra",
            "Gavrilov Posad",
            "Gaya",
            "Gaylord",
            "Gdov",
            "Gelendzhik",
            "Giaveno",
            "Gibraltar",
            "Glazunovka",
            "Gloucester",
            "Glubokiy",
            "Gokul",
            "Golitsyno",
            "Golubitskaya",
            "Gorelki",
            "Gorodets",
            "Gorokhovets",
            "Goryachevodskiy",
            "Goryachiy Klyuch",
            "Goshainganj",
            "Graaff-Reinet",
            "Grobenzell",
            "Grosuplje",
            "Grushevskaya",
            "Gunnedah",
            "Gurgaon",
            "Hall in Tirol",
            "Hangard",
            "Haradzishcha",
            "Haradzyeya",
            "Hardoi",
            "Hassloch",
            "Havana",
            "Hinesburg",
            "Hino",
            "Hodal",
            "Hola Prystan",
            "Holzgerlingen",
            "Horad Smalyavichy",
            "Horad Zhodzina",
            "Horsham",
            "Howick",
            "Howlong",
            "Hukuntsi",
            "Hulyaypole",
            "Huntingdon",
            "Iasi",
            "Iida",
            "Iksha",
            "Ilinskiy Pogost",
            "Illmensee",
            "Ilvesheim",
            "Imeni Vorovskogo",
            "Inashiki",
            "Inazawa",
            "Ingleburn",
            "Inkerman",
            "Inverell",
            "Inza",
            "Irkliyevskaya",
            "Irkutsk",
            "Isawa",
            "Isehara",
            "Ishioka",
            "Istra",
            "Itumba",
            "Ivanovo",
            "Izhevskoye",
            "Jaipur",
            "Jaisalmer",
            "Jalalabad",
            "Jiwani",
            "Jodhpur",
            "Kabardinka",
            "Kakori",
            "Kakrala",
            "Kalamaria",
            "Kalevala",
            "Kalininskaya",
            "Kamennomostskiy",
            "Kameshkovo",
            "Kamieniec Podolski",
            "Kamifukuoka",
            "Kanakapura",
            "Kanelovskaya",
            "Kanoya",
            "Kanpur",
            "Kapustin Yar",
            "Kapyl",
            "Karabanovo",
            "Karabash",
            "Kardonikskaya",
            "Karelichy",
            "Kasimov",
            "Kathmandu",
            "Kavala",
            "Kavkazskaya",
            "Kawasaki",
            "Kehrsatz",
            "Kerch",
            "Keswick",
            "Khadyzhensk",
            "Khajuraho",
            "Khalandrion",
            "Khanty-Mansiysk",
            "Kharkiv",
            "Khatanga",
            "Khatukay",
            "Khimki",
            "Khorlovo",
            "Khosta",
            "Khotkovo",
            "Khotyn",
            "Kidal",
            "Kideksha",
            "Kiev",
            "Kievskij",
            "Kimry",
            "Kiraoli",
            "Kirawsk",
            "Kirtipur",
            "Kirzhach",
            "Kiskunfelegyhaza",
            "Kitaibaraki",
            "Klimovsk",
            "Knevichi",
            "Kokorevka",
            "Kokshetau",
            "Koksovyy",
            "Koktebel",
            "Kolchugino",
            "Kolomyya",
            "Kommunar",
            "Komotini",
            "Konakovo",
            "Konobeyevo",
            "Korenovsk",
            "Kosi",
            "Kostroma",
            "Kotelnikovo",
            "Kotlas",
            "Kotputli",
            "Kovernino",
            "Kozani",
            "Kozlovo",
            "Kozmodemyansk",
            "Krasavino",
            "Krasnaya Polyana",
            "Krasnodar",
            "Krasnogorsk",
            "Krasnogvardeyskoye",
            "Krasnopavlivka",
            "Krasnoperekopsk",
            "Krasnoslobodsk",
            "Krasnoye-na-Volge",
            "Kratovo",
            "Kronshtadt",
            "Kropotkin",
            "Kryvyy Rih",
            "Kubanskiy",
            "Kubinka",
            "Kultuk",
            "Kurovskoye",
            "Kursk",
            "Kurumkan",
            "Kushchevskaya",
            "Kushuhum",
            "Kutulik",
            "Kuytun",
            "La Pocatiere",
            "Labinsk",
            "Ladozhskaya",
            "Lagrange",
            "Lahr",
            "Laichingen",
            "Lake Albert",
            "Lake of the Woods",
            "Larisa",
            "Lazarevskoye",
            "Leamington",
            "Legnago",
            "Leninsk",
            "Leon",
            "Les Mees",
            "Leskolovo",
            "Letea Veche",
            "Levashovo",
            "Levokumka",
            "LHospitalet de Llobregat",
            "Lichtenburg",
            "Likino-Dulevo",
            "Limache",
            "Lismore",
            "Llanes",
            "Lleida",
            "Llodio",
            "Loano",
            "Lodi",
            "Lodi",
            "Loeches",
            "Loffenau",
            "Loni",
            "Lopatinskiy",
            "Loukhi",
            "Lovere",
            "Lovozero",
            "Luchegorsk",
            "Lucknow",
            "Lukhovitsy",
            "Luzzi",
            "Lvovskiy",
            "Lytkarino",
            "Lyubertsy",
            "Lyubotyn",
            "Lyubuchany",
            "Mabopane",
            "Madrid",
            "Mafra",
            "Magole",
            "Mahilyow",
            "Mahwah",
            "Makaryev",
            "Malihabad",
            "Malino",
            "Malokaterynivka",
            "Mamontovka",
            "Mandra",
            "Manoharpur",
            "Mantes-la-Jolie",
            "Manturovo",
            "Marfino",
            "Mariupol",
            "Markha",
            "Marktoberdorf",
            "Marseille",
            "Martigny-Ville",
            "Masalovka",
            "Massandra",
            "Mathura",
            "Mayskiy",
            "Mazara del Vallo",
            "Medvedovskaya",
            "Medvezhyegorsk",
            "Medvode",
            "Megara",
            "Meliorativnoye",
            "Melissia",
            "Melitopol",
            "Menfi",
            "Mercedes",
            "Merefa",
            "Merida",
            "Merimbula",
            "Messina",
            "Messstetten",
            "Metamora",
            "Metsamor",
            "Mihail Kogalniceanu",
            "Mihara",
            "Mikhaylov",
            "Mikhnevo",
            "Mikhnevo",
            "Mineralnyye Vody",
            "Minsk",
            "Mir",
            "Mirnyy",
            "Mirnyy",
            "Misawa",
            "Miskhor",
            "Mitzpe Ramon",
            "Mokrous",
            "Mollendo",
            "Moncton",
            "Monino",
            "Monserrato",
            "Montecarlo",
            "Montelepre",
            "Montemurlo",
            "Montevideo",
            "Morata de Tajuna",
            "Morden",
            "Moree",
            "Morioka-shi",
            "Moron de la Frontera",
            "Morozovsk",
            "Moscow",
            "Mosrentgen",
            "Mount Isa",
            "Moyynty",
            "Mozzate",
            "Mstikhino",
            "Muenchen",
            "Mughal Sarai",
            "Mumbai",
            "Muranovo",
            "Murmino",
            "Murom",
            "Mynay",
            "Mysove",
            "Mytishchi",
            "Naberezhnyye Chelny",
            "Nadym",
            "Nagarkot",
            "Nagoya-shi",
            "Nakhabino",
            "Nalchik",
            "Namche Bazar",
            "Nanaimo",
            "Naraura",
            "Narbonne",
            "Narrabri",
            "Navahrudak",
            "Navlya",
            "Nea Ionia",
            "Nebug",
            "Necochea",
            "Neklyudovo",
            "Nemchinovka",
            "Nenzing",
            "Nerima",
            "Neryungri",
            "Neufahrn bei Freising",
            "Neuffen",
            "Nevinnomyssk",
            "New Delhi",
            "Nhulunbuy",
            "Nicosia",
            "Nigrita",
            "Niimi",
            "Nikita",
            "Nikolina Gora",
            "Ninomiya",
            "Nizhnevartovsk",
            "Nizhniy Novgorod",
            "Novobohdanivka",
            "Novocherkassk",
            "Novomikhaylovskiy",
            "Novomoskovsk",
            "Novooleksiyivka",
            "Novopetrovskoye",
            "Novopodrezkovo",
            "Novopokrovskaya",
            "Novorossiysk",
            "Novorozhdestvenskaya",
            "Novosibirsk",
            "Novotitarovskaya",
            "Novoukrainskiy",
            "Novozavidovskiy",
            "Novyy Urengoy",
            "Numazu",
            "Nyasvizh",
            "Nyuksenitsa",
            "O Carballino",
            "Oak Grove",
            "Obninsk",
            "Obolensk",
            "Obukhovo",
            "Odessa",
            "Olenegorsk",
            "Olevano Romano",
            "Olgiate Comasco",
            "Omsk",
            "Ono",
            "Opalikha",
            "Oral",
            "Orange",
            "Orapa",
            "Orekhovo-Zuyevo",
            "Orel",
            "Orel-Izumrud",
            "Orestiada",
            "Orlovskiy",
            "Orsha",
            "Ostrovtsy",
            "Otra Banda",
            "Outjo",
            "Ovsyanka",
            "Ozherelye",
            "Pak Chong",
            "Palekh",
            "Palencia",
            "Pali",
            "Palwal",
            "Panna",
            "Panyutyne",
            "Pargolovo",
            "Parkes",
            "Parkovyy",
            "Parksville",
            "Partenit",
            "Partyzany",
            "Pashkovskiy",
            "Patan",
            "Pavlohrad",
            "Pavlovskaya",
            "Pavlovskaya Sloboda",
            "Pavlovskiy Posad",
            "Pecatonica",
            "Pedara",
            "Perevalnoe",
            "Perlesreut",
            "Peschanokopskoye",
            "Peshawar",
            "Pestravka",
            "Pestyaki",
            "Petrodvorets",
            "Petropavlovsk",
            "Petrovo-Dalneye",
            "Petrozavodsk",
            "Petukhovo",
            "Pezinok",
            "Piacenza",
            "Piatra Neamt",
            "Piedimonte Matese",
            "Pietra la Croce",
            "Piraquara",
            "Pirassununga",
            "Pivdenne",
            "Pizzoli",
            "Plastunovskaya",
            "Ples",
            "Plessisville",
            "Plotnikovo",
            "Pokhara",
            "Pokotylivka",
            "Pokrov",
            "Poland",
            "Polistena",
            "Polur",
            "Polyany",
            "Pomarico",
            "Ponferrada",
            "Ponsacco",
            "Port Alberni",
            "Port Elizabeth",
            "Portage la Prairie",
            "Potenza",
            "Povarovo",
            "Pravdinskiy",
            "Pregradnaya",
            "Pressbaum",
            "Primorka",
            "Privodino",
            "Privolzhsk",
            "Privolzhskiy",
            "Proletarsk",
            "Pruzhany",
            "Pryshyb",
            "Pshada",
            "Puerto Rico",
            "Puertollano",
            "Punta Alta",
            "Pushkar",
            "Pushkino",
            "Pushkino",
            "Pyaozerskiy",
            "Pyatigorsk",
            "Quiliano",
            "Radauti",
            "Raduzhnyy",
            "Raipur",
            "Ramnagar",
            "Rasnov",
            "Rayevskaya",
            "Razvilka",
            "Rechitsy",
            "Rechka-Vydrino",
            "Reggio Calabria",
            "Reggio nellEmilia",
            "Remada",
            "Reshetnikovo",
            "Reutov",
            "Revyakino",
            "Rheinfelden (Baden)",
            "Rho",
            "Ribera",
            "Richelieu",
            "Richmond",
            "Rifu",
            "Riga",
            "Rimouski",
            "Rostov-na-Donu",
            "Rotorua",
            "Rottweil",
            "Rublevo",
            "Rusape",
            "Russkiy Kameshkir",
            "Ryazan",
            "Rybnoye",
            "Sadabad",
            "Sadovoye",
            "Saguenay",
            "Sahaswan",
            "Saint Petersburg",
            "Saint-Augustin-de-Desmaures",
            "Saint-Avertin",
            "Saint-Come--Liniere",
            "Sainte-Agathe-des-Monts",
            "Sainte-Marie",
            "Saint-Hyacinthe",
            "Saint-Jean-sur-Richelieu",
            "Saky",
            "Salekhard",
            "Salsk",
            "Salt",
            "Salto",
            "Samarskoye",
            "San Giovanni in Persiceto",
            "San Martino in Strada",
            "Sandila",
            "Sangano",
            "Sankt Georgen im Attergau",
            "Sant Adria de Besos",
            "Santa Pola",
            "Santana",
            "SantArcangelo di Romagna",
            "Santiago de Compostela",
            "Saratov",
            "Saratovskaya",
            "Saryshaghan",
            "Sary-Tyuz",
            "Sasaguri",
            "Satna",
            "Satrikh",
            "Savigny-sur-Orge",
            "Schifferstadt",
            "Sciez",
            "Selkirk",
            "Seltso",
            "Semkhoz",
            "Semypolky",
            "Sergiyev Posad",
            "Serpukhov",
            "Serres",
            "Sestao",
            "Sevastopol",
            "Severnoye",
            "Seymour",
            "Shahpura",
            "Sharya",
            "Shaturtorf",
            "Shchebetovka",
            "Shchelkovo",
            "Shchuchinsk",
            "Shelekhov",
            "Shepparton",
            "Shepsi",
            "Shikarpur",
            "Shiki",
            "Shimodate",
            "Shizuoka-shi",
            "Shklow",
            "Shu",
            "Sibiu",
            "Skhodnya",
            "Skoropuskovskiy",
            "Slatino",
            "Slavyansk-na-Kubani",
            "Slonim",
            "Slyudyanka",
            "Smidovich",
            "Smiths Falls",
            "Smolensk",
            "Sochi",
            "Sofrino",
            "Soka",
            "Sokhumi",
            "Sokol",
            "Soligalich",
            "Solnechnogorsk",
            "Solotcha",
            "Soluno-Dmitriyevskoye",
            "Sonthofen",
            "Soria",
            "Spassk-Ryazanskiy",
            "Spotorno",
            "Srednyaya Akhtuba",
            "Stantsiya Novyy Afon",
            "Staraya",
            "Staraya Stanitsa",
            "Staroleushkovskaya",
            "Starominskaya",
            "Staronizhestebliyevskaya",
            "Starotitarovskaya",
            "Staryy Krym",
            "Staryy Oskol",
            "Stavropol",
            "Stavyshche",
            "Stellenbosch",
            "Stolbovaya",
            "Strelna",
            "Strunino",
            "Stupino",
            "Sturgis",
            "Sturno",
            "Suances",
            "Suceava",
            "Sudak",
            "Sukagawa",
            "Sumoto",
            "Surovikino",
            "Susanino",
            "Suvorovskaya",
            "Suzdal",
            "Suzemka",
            "Swan Hill",
            "Tabaquite",
            "Tagerwilen",
            "Taigum",
            "Talaja",
            "Tarasovskiy",
            "Tarusa",
            "Tautii Magherus",
            "Tazlar",
            "Teggiano",
            "Temryuk",
            "Tennant Creek",
            "Terbuny",
            "Ternevskaya",
            "Ternitz",
            "Terny",
            "Terrassa",
            "Thessaloniki",
            "Thionville",
            "Thoiry",
            "Thorold",
            "Thunder Bay",
            "Tikaitnagar",
            "Tikhoretsk",
            "Tiksi",
            "Timaru",
            "Timashevsk",
            "Titisee-Neustadt",
            "Tlyustenkhabl",
            "Tokmak",
            "Toluca",
            "Tom Price",
            "Tomilino",
            "Tondabayashi",
            "Torrita di Siena",
            "Totma",
            "Tracadie-Sheila",
            "Trouy",
            "Trudobelikovskiy",
            "Tsumeb",
            "Tsu-shi",
            "Tuapse",
            "Tuchkovo",
            "Tula",
            "Tularosa",
            "Tulun",
            "Turkheim",
            "Tursi",
            "Turuntayevo",
            "Udachnyy",
            "Udaipur",
            "Ufa",
            "Uglovoye",
            "Ujhani",
            "Ukhta",
            "Ulu-Telyak",
            "Ulyanovsk",
            "Umi",
            "Upata",
            "Urbach",
            "Usehat",
            "Usolye-Sibirskoye",
            "Ussuriysk",
            "Ust-Barguzin",
            "Ust-Katav",
            "Ust-Labinsk",
            "Uyutne",
            "Uzhhorod",
            "Vado Ligure",
            "Valday",
            "Valdidentro",
            "Valencia West",
            "Valls",
            "Vanavara",
            "Vancouver",
            "Varanasi",
            "Vardane",
            "Vasilikon",
            "Vasylivka",
            "Vatutinki",
            "Vega de Espinareda",
            "Velikiy Ustyug",
            "Velke Mezirici",
            "Veniano",
            "Verano Brianza",
            "Verbilki",
            "Verkhovye",
            "Verona",
            "Veshkayma",
            "Vienna",
            "Villa Literno",
            "Villa Nueva",
            "Villar Focchiardo",
            "Vinogradnyy",
            "Vityazevo",
            "Vnukovo",
            "Vorkuta",
            "Vorokhta",
            "Voronezh",
            "Voskresensk",
            "Vostochnyy",
            "Vostryakovo",
            "Vovchansk",
            "Vyazemskiy",
            "Vyselki",
            "Vysokoye",
            "Vysokyy",
            "Wanaque",
            "Waterloo",
            "Welkom",
            "West Kelowna",
            "Woodville",
            "Xanthi",
            "Xiaolingwei",
            "Yakovlevskoye",
            "Yakymivka",
            "Yalta",
            "Yam",
            "Yampil",
            "Yamunanagar",
            "Yantarnyy",
            "Yaremche",
            "Yaroslavl",
            "Yasnogorsk",
            "Yegoryevsk",
            "Yelatma",
            "Yeri",
            "Yevpatoriya",
            "Yeysk",
            "Yubileyny",
            "Yukuhashi",
            "Yuryev-Polskiy",
            "Yuzha",
            "Zaidpur",
            "Zakynthos",
            "Zalari",
            "Zalegoshch",
            "Zalishchyky",
            "Zaokskiy",
            "Zaporizhzhya",
            "Zaraysk",
            "Zasechnoye",
            "Zavolzhye",
            "Zaysan",
            "Zelenograd",
            "Zelenogradskiy",
            "Zeltweg",
            "Zhavoronki",
            "Zheleznodorozhnyy",
            "Zhukovskiy",
            "Zimovniki",
            "Zmiyevka",
            "Zofingen",
            "Zolotukhino",
            "Zvenigorod",
            "Zvenigovo"
    };
}
